version: '3.8'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - tests_network
    hostname: website

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 7900:7900
    shm_size: "2g"
    platform: "linux/amd64"
    networks:
      - tests_network

  test_runner:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - $PWD:/usr/app
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - WEBSITE_HOST=website
    entrypoint: npm
    command:
      - test
    networks:
      - tests_network

networks:
  tests_network:
